---
- name: ensure the parent directory for hidden services exists
  file:
    state: directory
    dest: "{{ tor_hidden_services_parent_dir }}"
    owner: "{{ tor_user }}"
    group: "{{ tor_user }}"
    mode: '0700'
  tags:
    - tor

- name: ensure each hidden service's directory exists
  file:
    state: directory
    dest: "{{ tor_hidden_services_parent_dir }}/{{ item.service }}"
    owner: "{{ tor_user }}"
    group: "{{ tor_user }}"
    mode: '0700'
  with_items: tor_instances
  tags:
    - tor

- name: ensure securedrop server torrc is present
  template:
    src: torrc
    dest: /etc/tor/torrc
    owner: "{{ tor_user }}"
    group: "{{ tor_user }}"
    mode: '0644'
  notify:
    - restart tor
  tags:
    - tor

- meta: flush_handlers
  tags:
    - tor

- name: ensure tor is running
  service:
    name: tor
    state: running
  tags:
    - tor
