---
  # If the OSSEC authd iptable rule exemptions are in place, remove them and
  # restart OSSEC. This role must run on the app server first and then on
  # the monitor server. This order is important, since the app server's
  # OSSEC agent needs to restart to load the imported cert from authd and
  # connect to the ossec server. The monitor server's OSSEC service needs to
  # restart after the agent connects to correctly display the agent status.
- name: Remove firewall exemptions for OSSEC authd registration.
  lineinfile:
    state: absent
    dest: /etc/network/iptables/rules_v4
    # last line in the initial *filter stanza (which must come before any rules)
    # rules will be applied before the default rules defined in rules_v4 file
    line: "{{ item }}"
  notify:
    - reload iptables rules
    - restart ossec
  with_items: authd_rules
  tags:
    - iptables
    - ossec_auth

- name: Kill authd process if running.
  # This should work using the pattern to grep for in the output of ps per
  # http://docs.ansible.com/service_module.html
  # Currently getting an error saying
  # failed: [mon-staging] => {"failed": true}
  #  msg: service not found: ossec-authd
  #service: name=ossec-authd pattern=/var/ossec/bin/ossec-authd state=started
  shell: "pkill ossec-authd || true"
  tags:
    - iptables
    - ossec_auth
    - authd
