---
- name: Validate presence of Application and Monitor Servers.
  hosts: [ mon, app, mon-prod, app-prod ]
  roles:
    - { role: manage-groups, tags: manage-groups }

- name: Validate instance-specific variables before provisioning.
  hosts: securedrop
  vars_files:
    - prod-specific.yml
  roles:
    - { role: validate, tags: validate }
  sudo: yes

- name: Add FPF apt repository and install base packages.
  hosts: securedrop
  roles:
    - { role: common, tags: common }
  sudo: yes

- name: Configure SecureDrop Monitor Server.
  hosts: securedrop_monitor_server
  vars_files:
    - prod-specific.yml
  roles:
    - { role: ossec_server, tags: [ ossec, ossec_server ] }
  sudo: yes

- name: Configure SecureDrop Application Server.
  hosts: securedrop_application_server
  vars_files:
   - prod-specific.yml
  vars:
  roles:
    - { role: ossec_agent, tags: [ ossec, ossec_agent ] }
    - { role: app, tags: app }
  sudo: yes

  # If the OSSEC authd iptables rule exemptions are in place remove them and
  # restart OSSEC. For the ossec agent the exemptions are removed as part of
  # the authd role, in order to allow all agents to connect to the ossec server
  # before killing authd and removing the ossec rules. This is a separate role for
  # the ossec server. The order of events does matter: the monitor server authd
  # service needs to be listening and reachable, then agent needs to connect to
  # ossec server, agent needs to restart, then ossec server exemptions can be
  # removed and the ossec server process can restart.
- name: Remove temporary firewall exemptions from Monitor Server.
  hosts: securedrop_monitor_server
  vars_files:
    - prod-specific.yml
  roles:
    - { role: remove_authd_exemptions, tags: [ ossec, ossec_server, remove_authd_exemptions ] }
  sudo: yes

  # This section will put the ssh and iptables rules in place
  # It will then add any staging exemptions required
  # at the end of each host section is when the handlers are run.
  # So iptables will not be reloaded until the exemptions are applied
  # for production the last task is apply iptables. This will break their
  # connection. After that point the admin will to proxy traffic over tor.
  name: Lock down firewall configuration for Application and Monitor Servers.
  hosts: securedrop
  vars_files:
    - prod-specific.yml
  roles:
    - { role: restrict-direct-access, tags: [ common, restrict-direct-access ] }
  sudo: yes

- name: Perform backup of Application Server configuration.
  hosts: securedrop_application_server
  vars_files:
    - prod-specific.yml
  roles:
    - { role: backup, tags: backup }
  sudo: yes

- name: Reboot Application and Monitor Servers.
  hosts: securedrop
  vars_files:
    - prod-specific.yml
  roles:
    - { role: reboot, tags: reboot }
  sudo: yes
