---
- name: Add FPF apt repository and install base packages.
  hosts: staging
  roles:
    - { role: common, tags: common }
    - { role: install_local_pkgs, tags: install_local_pkgs,
        when: install_local_packages }
  sudo: yes

- name: Configure OSSEC manager.
  hosts: mon-staging
  roles:
    - { role: ossec_server, tags: ['ossec', 'ossec_server'] }
  sudo: yes

- name: Configure SecureDrop Application Server.
  hosts: app-staging
  roles:
    # The common-app role should be renamed.
    # It installs tor. Tor is required to be installed prior to the securedrop
    # app-code package which contains an apparmor profile that depends on tor
    # being present.
    # this is a staging only role
    - { role: ossec_agent, tags: [ 'ossec', 'ossec_agent' ] }
    - { role: app, tags: app }
    - { role: app-test, tags: app-test }
  sudo: yes

  # If the OSSEC authd iptables rule exemptions are in place remove them and
  # restart OSSEC. For the ossec agent the exemptions are removed as part of
  # the authd role, in order to allow all agents to connect to the ossec server
  # before killing authd and removing the ossec rules. This is a separate role for
  # the ossec server. The order of events does matter: the monitor server authd
  # service needs to be listening and reachable, then agent needs to connect to
  # ossec server, agent needs to restart, then ossec server exemptions can be
  # removed and the ossec server process can restart.
- name: Remove temporary firewall exemptions from Monitor Server.
  hosts: mon-staging
  roles:
    - { role: remove_authd_exemptions, tags: ['ossec', 'ossec_server', 'remove_authd_exemptions' ] }
  sudo: yes

  # This section will put the ssh and iptables rules in place
  # It will then add any staging exemptions required
  # at the end of each host section is when the handlers are run.
  # So iptables will not be reloaded until the exemptions are applied
  # for production the last task is apply iptables. This will break their
  # connection. After that point the admin will to proxy traffic over tor.
- name: Configure host firewalls (with direct access for staging).
  hosts: staging
  roles:
    - { role: restrict-direct-access, tags: [ common, restrict-direct-access ] }
    - { role: allow-direct-access, tags: [ common, allow_direct_access ] }
  sudo: yes

- name: Perform backup of Application Server configuration.
  hosts: app-staging
  roles:
    - { role: backup, tags: backup }
  sudo: yes
