---
- name: Install OSSEC manager package.
  apt:
    name: securedrop-ossec-server
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - apt

- name: Install procmail.
  apt:
    name: procmail
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - apt
    - procmail

- name: Copy the OSSEC GPG public key for sending encrypted alerts.
  copy:
    src: "{{ ossec_alert_gpg_public_key }}"
    dest: /var/ossec
  tags:
    - gpg

- name: Add the OSSEC GPG public key to the OSSEC manager keyring.
  # multiline format for command module, since this is a long command
  command: >
    su -s /bin/bash -c 'gpg
    --homedir /var/ossec/.gnupg
    --import /var/ossec/{{ ossec_alert_gpg_public_key }}' {{ ossec_group }}
  tags:
    - gpg

- name: Copy script for sending GPG-encrypted OSSEC alerts.
  template:
    src: send_encrypted_alarm.sh
    dest: /var/ossec/send_encrypted_alarm.sh
    mode: 775
    owner: ossec
    group: root
  tags:
    - procmail
    - permissions

  # TODO This might not be necessary
- name: Create procmail log file.
  file:
    state: touch
    dest: /var/log/procmail.log
    mode: 660
    owner: ossec
    group: root
  tags:
    - procmail
    - permissions
    - logging

- name: Copy procmail config file.
  copy:
    src: procmailrc
    dest: /var/ossec/.procmailrc
    owner: ossec
    group: root
  tags:
    - procmail
