---
- name: Copy sudoers file.
  copy:
    src: sudoers
    dest: /etc/sudoers
    owner: root
    group: root
    mode: '0440'
    backup: yes
    validate: "visudo -cf %s"
  register: sudoers_st
  tags:
    - users
    - sudoers

- name: Create shell accounts for SecureDrop admins.
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: sudo,ssh
  with_items: ssh_users
  tags:
    - users
    - sudoers

  # TODO: consider moving this to /etc/profile.d,
  # so subsequent task modifiying .bashrc files
  # can be removed. (Don't forget to include .sh
  # on dest file if in /etc/profile.d)
- name: copy SecureDrop bashrc additions
  copy:
    src: bashrc_securedrop_additions
    dest: /etc/bashrc.securedrop_additions
    owner: root
    group: root
    mode: 0644
  tags:
    - users
    - environment

  # TODO: see above; if environment config is moved
  # to /etc/profile.d, this task can be removed altogether.
- name: add line to each users bashrc to source the SecureDrop additions
  lineinfile:
    dest: /home/{{ item }}/.bashrc
    line: '. /etc/bashrc.securedrop_additions'
    insertbefore: BOF
  with_items: ssh_users
  tags:
    - users
    - environment
