---
  # Since production environment does not have DHCP or DNS,
  # create hard-coded /etc/hosts entries with assigned local IP addresses.
- name: ensure /etc/hosts file has entry for app and monitor servers
  lineinfile:
    backup: yes
    dest: /etc/hosts
    insertafter: EOF
    line: "{{ item.ip }}  {{ item.hostname }}"
    regexp: "^{{ item.ip }}    {{ item.hostname }}"
  with_items: ip_info
  tags:
    - host_aliases
    - static-hosts

