---
- name: wait for all tor hidden services hostname files
  wait_for:
    state: present
    path: "{{ tor_hidden_services_parent_dir }}/{{ item.service }}/hostname"
    delay: 5
  with_items: tor_instances
  tags:
    - tor

- name: fetch tor hidden service config files
  fetch:
    src: /var/lib/tor/services/{{ item.service }}/hostname
    dest: ./{{ item.filename }}
    flat: yes
    fail_on_missing: yes
  tags:
    - tor
    - fetch
    - admin

  # These tasks modifies the fetched copy of the server's aths info to
  # format it for a torrc file on the admins workstation.
  # This should make it easier for the admin or journalist to copy paste the
  # line correctly.
- name: format securedrop aths files
  local_action: lineinfile
    dest=./{{ item.filename }}
    regexp='(.*)'
    backrefs=yes
    line='HidServAuth \1'
  sudo: no
  with_items: tor_instances
  tags:
    - tor
    - admin
