---
# After installing securedrop-grsec, remove
# old generic kernels to avoid accidental
# boots into a less secure environment.
- name: Remove generic kernel metapackages.
  apt:
    name: "{{item}}"
    state: absent
  with_items:
    - linux-signed-generic
    - linux-signed-generic-lts-utopic
    - linux-signed-image-generic
    - linux-signed-image-generic-lts-utopic
  tags:
    - apt

- name: Remove remaining generic kernels.
  command: apt-get -y remove '^linux-image-.*generic$'
  register: linux_image_removal
  changed_when: "'0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.' not in linux_image_removal.stdout"
  tags:
    - apt

- name: Remove remaining kernel headers.
  command: apt-get -y remove '^linux-headers-.*'
  register: linux_headers_removal
  changed_when: "'0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.' not in linux_headers_removal.stdout"
  tags:
    - apt

- name: Mark GRUB2 as manually installed so its not removed.
  command: apt-mark manual grub-pc
  register: grubpc_manual_mark
  changed_when: "'grub-pc was already set to manually installed.' not in grubpc_manual_mark.stdout"
  tags:
    - apt
    - kernel
    - grub

- name: Clean old apt packages.
  command: apt-get -y autoremove
  register: apt_autoremove_all
  changed_when: "'0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.' not in apt_autoremove_all.stdout"
  tags:
    - apt
